server:
  port: 922
spring:
  profiles:
    active: ${spring.profiles.default:local}
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB